blank_issues_enabled: false
contact_links:
  - name: Questions and discussion
    url: https://github.com/omar-hanafy/convert_object/discussions
    about: Please ask and answer general questions here.
